version: "3"

services:

  wordpress:
    build:
      context: ./wordpress
    image: wordpress
    container_name: "inception_wordpress"
    environment:
      - WP_URL=https://${DOMAIN_NAME}
      - WP_DATABASE=${WP_DATABASE}
      - WP_TITLE=${WP_TITLE}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PWD=${WP_ADMIN_PWD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_PORT=${MARIADB_PORT}
      - PHP_FPM_PORT=${PHP_FPM_PORT}
    volumes:
      - wordpress-volume:/var/www/wordpress
    restart: unless-stopped

  # ------------------------------------------------------------------------- #

  mariadb:
    build:
      context: ./mariadb
    container_name: "inception_mariadb"
    image: mariadb
    environment:
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_PORT=${MARIADB_PORT}
    volumes:
      - mariadb-volume:/var/lib/mysql
    restart: unless-stopped 

  # ------------------------------------------------------------------------- #

  nginx:
    build:
      context: ./nginx
    container_name: "inception_nginx"
    image: nginx
    ports:
      - "443:443"
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - CERTS_DIR=${CERTS_DIR}
      - TLS_VERSION=${TLS_VERSION}
      - PHP_FPM_HOST=${PHP_FPM_HOST}
      - PHP_FPM_PORT=${PHP_FPM_PORT}
    volumes:
      - wordpress-volume:/var/www/wordpress
    restart: unless-stopped 

  # ------------------------------------------------------------------------- #

  redis:
    build:
      context: ./redis
    container_name: "inception_redis_wp_cache"
    image: redis

volumes:
  mariadb-volume:
    driver: local
    driver_opts:
      type: none
      device: ${MARIADB_HOST_VOLUME_PATH}
      o: bind
  wordpress-volume:
    driver: local
    driver_opts:
      type: none
      device: ${WP_HOST_VOLUME_PATH}
      o: bind
