version: "3"
services:
  wordpress:
    build:
      context: ./wordpress
    image: wordpress
    container_name: "inception_wordpress"
    environment:
      - WP_URL=${WORDPRESS_URL}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    volumes:
      - wordpress-volume:/var/www/wordpress
  mariadb:
    build:
      context: ./mariadb
    container_name: "inception_mariadb"
    image: mariadb
    environment:
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    volumes:
      - mariadb-volume:/var/lib/mysql
  nginx:
    build:
      context: ./nginx
    container_name: "inception_nginx"
    image: nginx
    ports:
      - "80:80"
    volumes:
      - wordpress-volume:/var/www/wordpress

volumes:
  mariadb-volume:
    driver: local
    driver_opts:
      type: none
      device: ${MARIADB_HOST_VOLUME_PATH}
      o: bind
  wordpress-volume:
    driver: local
    driver_opts:
      type: none
      device: ${WORDPRESS_HOST_VOLUME_PATH}
      o: bind
