version: "3"
services:
  wordpress:
    build:
      context: ./wordpress
    image: wordpress
    container_name: "inception_wordpress"
    environment:
      - WP_URL=${WP_URL}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    volumes:
      - wordpress-volume:/var/www/wordpress
  mariadb:
    build:
      context: ./mariadb
    container_name: "inception_mariadb"
    image: mariadb
    environment:
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    volumes:
      - mariadb-volume:/var/lib/mysql
  nginx:
    build:
      context: ./nginx
    container_name: "inception_nginx"
    image: nginx
    ports:
      - "443:443"
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - CERTS_DIR=${CERTS_DIR}
      - TLS_VERSION=${TLS_VERSION}
      - PHP_FPM_HOST=${PHP_FPM_HOST}
      - PHP_FPM_PORT=${PHP_FPM_PORT}
    volumes:
      - wordpress-volume:/var/www/wordpress

volumes:
  mariadb-volume:
    driver: local
    driver_opts:
      type: none
      device: ${MARIADB_HOST_VOLUME_PATH}
      o: bind
  wordpress-volume:
    driver: local
    driver_opts:
      type: none
      device: ${WP_HOST_VOLUME_PATH}
      o: bind
