#! /bin/sh

i=1
while ! test -f "${CERTS_DIR}/${DOMAIN_NAME}.crt" || ! test -f "${CERTS_DIR}/${DOMAIN_NAME}.key"; do
	if [ $i -ge 120 ]; then
		printf "Could not setup TLS for adminer!\n"
		exit 1
	fi
	printf "Waiting for SSL certificate to be generated by nginx container... ($i/120 sec)\n"
	i=$(($i+1))
	sleep 1
done

# Edit nginx configuration to fit provided environment
sed -i "s|CERT_TEMPLATE|${CERTS_DIR}/${DOMAIN_NAME}|g" /etc/nginx/http.d/default.conf
sed -i "s|KEY_TEMPLATE|${CERTS_DIR}/${DOMAIN_NAME}|g" /etc/nginx/http.d/default.conf
sed -i "s/TLS_VERSION_TEMPLATE/${TLS_VERSION}/g" /etc/nginx/http.d/default.conf
sed -i "s/SERVER_NAME_TEMPLATE/${DOMAIN_NAME}/g" /etc/nginx/http.d/default.conf
sed -i "s/LISTEN_TEMPLATE/${ADMINER_PORT}/g" /etc/nginx/http.d/default.conf

php-fpm7
nginx -g "daemon off;"
