#! /bin/sh

i=1
while ! test -f "${CERTS_DIR}/${DOMAIN_NAME}.crt" || ! test -f "${CERTS_DIR}/${DOMAIN_NAME}.key"; do
	if [ $i -ge 120 ]; then
		printf "Could not setup FTPS correctly!\n"
		exit 1
	fi
	printf "Waiting for SSL certificate to be generated by nginx container... ($i/120 sec)\n"
	i=$(($i+1))
	sleep 1
done

chgrp -R ftp_user /home/ftp_user
chmod -R g-w /home/ftp_user

vsftpd /etc/vsftpd/vsftpd.conf
