#! /bin/sh

i=1
while ! test -f "${CERTS_DIR}/${DOMAIN_NAME}.crt" || ! test -f "${CERTS_DIR}/${DOMAIN_NAME}.key"; do
	if [ $i -ge 120 ]; then
		printf "Could not setup FTPS correctly!\n"
		exit 1
	fi
	printf "Waiting for SSL certificate to be generated by nginx container... ($i/120 sec)\n"
	i=$(($i+1))
	sleep 1
done

{ echo "$FTP_PASSWORD"; echo "$FTP_PASSWORD"; } | adduser $FTP_USER

chgrp -R $FTP_USER /home/$FTP_USER
chmod -R g-w /home/$FTP_USER

vsftpd /etc/vsftpd/vsftpd.conf
